stages:
  - test
  - deploy

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
- curl -sS https://getcomposer.org/installer | php >/dev/null 2>&1
- php composer.phar install >/dev/null 2>&1
- composer.phar require --dev jakub-onderka/php-parallel-lint >/dev/null 2>&1
- wget https://github.com/Block8/php-docblock-checker/archive/1.3.4.zip >/dev/null 2>&1
- unzip 1.3.4.zip >/dev/null 2>&1
- rm 1.3.4.zip
- cd php-docblock-checker-1.3.4/
- php ../composer.phar install >/dev/null 2>&1
- cd ../
- php composer.phar require phpspec/phpspec >/dev/null 2>&1

# Run our tests
test:php:
  stage: test
  script:
  - ./php-docblock-checker-1.3.4/vendor/bin/phploc inc
  - ./php-docblock-checker-1.3.4/vendor/bin/phpcs --standard="PSR1,PSR2" --ignore="vendor,library,php-docblock-checker-1.3.4,phpspec" ./
  - ./vendor/bin/parallel-lint --exclude library --exclude vendor --exclude php-docblock-checker-1.3.4 --exclude phpspec --blame -e php .
  - ./vendor/phpspec/phpspec/bin/phpspec run

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.itsabeta.nx
  when: manual
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  when: manual
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://nxfifteen.me.uk/api/fitbit/
  when: manual
  only:
  - master