stages:
  - test
  - deploy

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
- curl -sS https://getcomposer.org/installer | php >/dev/null 2>&1
- php composer.phar install >/dev/null 2>&1
- wget https://phar.phpunit.de/phploc.phar >/dev/null 2>&1

# Run our tests
test:phploc:
  stage: test
  script:
  - php phploc.phar inc

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
  - master