stages:
  - syntax
  - test
  - info
  - review
  - stage
  - deploy

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
 - bash ./dev/build_dev_env.sh

# Run our tests
test:phpcs:
  stage: syntax
  script:
  - bash ./dev/phpcs_cbf.sh

# Run our tests
test:php:
  stage: test
  script:
  - php phpunit.phar
  - ./vendor/bin/parallel-lint --exclude library --exclude vendor --exclude php-docblock-checker-1.3.4 --exclude phpspec --blame -e php .
  - ./vendor/phpspec/phpspec/bin/phpspec run

# Run our tests
test:phploc:
  stage: info
  script:
  - ./php-docblock-checker-1.3.4/vendor/bin/phploc inc

deploy_review:
  stage: review
  script:
    - echo "Deploy a review app"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh nxad@nxfifteen.me.uk /home/nxad/homes/gitrepos/deploy_review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.itsabeta.nx
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: stage
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  when: manual
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://nxfifteen.me.uk/api/fitbit/
  when: manual
  only:
  - master