image: php:7.1.4

stages:
  - test
  - stage
  - deploy

# Select what we should cache between builds
cache:
  paths:
  - bundle/vendor/
  - binaries/

before_script:
  - sh ./dev/build_dev_env.sh

codeclimate:
  stage: test
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]

deploy_review:
  stage: stage
  script:
    - echo "Deploy a review app"
    - wget -O /tmp/deploy https://nxfifteen.me.uk/gitlab/nx-fitness/nxfitness-core/raw/$CI_COMMIT_REF_NAME/dev/deploy_review
    - bash /tmp/deploy "$REVIEW_PATH" $CI_COMMIT_REF_NAME $CI_ENVIRONMENT_SLUG
    - rm -f /tmp/deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://docs.core.itsabeta.nx/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: stage
  script:
    - echo "Deploy to staging server"
    - wget -O /tmp/deploy https://nxfifteen.me.uk/gitlab/nx-fitness/nxfitness-core/raw/$CI_COMMIT_REF_NAME/dev/deploy_staging
    - bash /tmp/deploy "$STAGING_PATH/$CI_ENVIRONMENT_SLUG" $CI_COMMIT_REF_NAME $CI_ENVIRONMENT_SLUG
    - rm -f /tmp/deploy
  environment:
    name: staging
    url: http://core.itsabeta.nx/$CI_ENVIRONMENT_SLUG/ux/
  only:
    - branches
  except:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - scp ./dev/deploy_prod nxad@nxfifteen.me.uk:/home/nxad/homes/gitrepos/deploy_prod
    - ssh nxad@nxfifteen.me.uk chmod 755 /home/nxad/homes/gitrepos/deploy_prod
    - ssh nxad@nxfifteen.me.uk /home/nxad/homes/gitrepos/deploy_prod
  environment:
    name: production
    url: https://nxfifteen.me.uk/api/fitbit/
  only:
  - master
