# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.1.4-alpine

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
# Install and run Composer
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- wget https://phar.phpunit.de/phploc.phar

# Run our tests
test:phploc:
  script:
  - php /usr/local/bin/phploc inc