stages:
  - test
  - syntax
  - info
  - review
  - stage
  - deploy

# Select what we should cache between builds
cache:
  paths:
  - vendor/
  - binaries/

# Run our tests
test:php:
  stage: test
  before_script:
  - bash ./dev/build_dev_env.sh
  script:
  - php ./binaries/phpunit.phar -c phpunit.xml
  - ./vendor/bin/parallel-lint --exclude library --exclude vendor --exclude binaries/php-docblock-checker-1.3.4 --exclude binaries/phpspec --blame -e php .
  - ./vendor/phpspec/phpspec/bin/phpspec run

# Run our tests
test:phpcs:
  stage: syntax
  before_script:
  - bash ./dev/build_dev_env.sh
  script:
  - bash ./dev/phpcs_cbf.sh

# Run our tests
test:phploc:
  stage: info
  before_script:
  - bash ./dev/build_dev_env.sh
  script:
  - ./binaries/php-docblock-checker-1.3.4/vendor/bin/phploc inc

deploy_review:
  stage: review
  script:
    - echo "Deploy a review app"
    - /home/nxad/gits/deploy_review "$STAGING_PATH" $CI_COMMIT_REF_NAME $CI_ENVIRONMENT_SLUG
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://docs.core.itsabeta.nx/
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: stage
  script:
    - echo "Deploy to staging server"
    - /home/nxad/gits/deploy_staging "$STAGING_PATH" $CI_COMMIT_REF_NAME $CI_ENVIRONMENT_SLUG
  environment:
    name: staging
    url: http://fit.itsabeta.nx/api/$CI_ENVIRONMENT_SLUG/ux/
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh nxad@nxfifteen.me.uk /home/nxad/homes/gitrepos/deploy_prod
  environment:
    name: production
    url: https://nxfifteen.me.uk/api/fitbit/
  when: manual
  only:
  - master