#!/bin/bash
ROOTPATH="$1"
CI_COMMIT_REF_NAME="$2"
CI_ENVIRONMENT_SLUG="$3"

eval $(ssh-agent -s)
ssh-add $HOME/id_rsa_nxcore

if [ ! -d "$ROOTPATH" ]; then
    mkdir -p "$ROOTPATH"
    cd "$ROOTPATH"
    git clone git@nxfifteen.me.uk:nx-fitness/nxfitness-core.git ./
else
    cd "$ROOTPATH"
fi

cd "$ROOTPATH"
git checkout .
git checkout $CI_COMMIT_REF_NAME
git pull

bash "$ROOTPATH/dev/genDocs" "$ROOTPATH"

killall -9 ssh-agent
