#!/bin/bash
ROOTPATH="$1"
CI_COMMIT_REF_NAME="$2"
CI_ENVIRONMENT_SLUG="$3"

SSHAGENT=`which ssh-agent`
SSHAGENTARGS="-s"
if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT" ]; then
    eval `$SSHAGENT $SSHAGENTARGS`
    trap "kill $SSH_AGENT_PID" 0
fi

ssh-add /home/gitlab-runner/id_rsa_nxcore

echo "Staging $CI_COMMIT_REF_NAME in $ROOTPATH"

if [ ! -d "$ROOTPATH" ]; then
    mkdir -p "$ROOTPATH"
    cd "$ROOTPATH"
    git clone git@nxfifteen.me.uk:nx-fitness/nxfitness-core.git ./
else
    cd "$ROOTPATH"
fi

cd "$ROOTPATH"
git clean -df
git checkout -- .
git checkout $CI_COMMIT_REF_NAME
git pull

bash "$ROOTPATH/dev/genDocs" "$ROOTPATH"

if [ ${SSH_AGENT_PID+1} == 1 ]; then
    ssh-add -D
    ssh-agent -k > /dev/null 2>&1
    unset SSH_AGENT_PID
    unset SSH_AUTH_SOCK
fi
