#!/bin/bash
CI_COMMIT_REF_NAME="$1"
CI_ENVIRONMENT_SLUG="$2"

SSHAGENT=`which ssh-agent`
SSHAGENTARGS="-s"
if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT" ]; then
    eval `$SSHAGENT $SSHAGENTARGS`
    trap "kill $SSH_AGENT_PID" 0
fi
ssh-add /home/nxad/.ssh/id_rsa_deploy

if [ -d "/home/nxad/public_html/api/fitbit" ]; then
    cd "/home/nxad/public_html/api/fitbit"
    git checkout .
    git checkout master
    git pull

    php5 ./get.php --user=269VLG --get=nomie_trackers

    echo "**** Master Patch Applied ****" >> "/home/nxad/public_html/api/fitbit/fitbit.log"
fi

if [ ${SSH_AGENT_PID+1} == 1 ]; then
    ssh-add -D
    ssh-agent -k > /dev/null 2>&1
    unset SSH_AGENT_PID
    unset SSH_AUTH_SOCK
fi
