#!/bin/bash
ROOTPATH="$1"
CI_COMMIT_REF_NAME="$2"
CI_ENVIRONMENT_SLUG="$3"

eval $(ssh-agent -s)
ssh-add /home/nxad/.ssh/id_rsa_pss

if [ ! -d "$ROOTPATH" ]; then
    mkdir "$ROOTPATH"
    cd "$ROOTPATH"
    git clone git@nxfifteen.me.uk:nx-fitness/nxfitness-core.git ./
else
    cd "$ROOTPATH"
fi

cd "$ROOTPATH"
git checkout develop
git pull

if [ ! -d "$ROOTPATH/binaries" ]; then
    echo "***creating binaries"
    mkdir "$ROOTPATH/binaries"
fi

if [ ! -f "composer.phar" ]; then
    echo "***downloading composer"
    cd "$ROOTPATH/binaries"
    curl -sS https://getcomposer.org/installer | php >/dev/null 2>&1
    cd "$ROOTPATH"

    echo "***running composer install dev"
    php "$ROOTPATH/binaries/composer.phar" install --dev >/dev/null 2>&1
else

    echo "***running composer update dev"
    php "$ROOTPATH/binaries/composer.phar" update --dev >/dev/null 2>&1
fi

php "$ROOTPATH/vendor/phpdocumentor/phpdocumentor/bin/phpdoc"  >/dev/null 2>&1
cd "$ROOTPATH/docs/wiki.core"
rsync -vhru --delete-after ./docs/development/* /var/www/dev/development/

