#!/bin/bash
ROOTPATH="$1"
CI_COMMIT_REF_NAME="$2"
CI_ENVIRONMENT_SLUG="$3"

eval $(ssh-agent -s)

ssh-add $HOME/id_rsa_nxcore

if [ ! -d "$ROOTPATH" ]; then
    mkdir -p "$ROOTPATH"
    cd "$ROOTPATH"
    git clone git@nxfifteen.me.uk:nx-fitness/nxfitness-core.git ./
else
    cd "$ROOTPATH"
fi

cd "$ROOTPATH"
git checkout $CI_COMMIT_REF_NAME
git pull

if [ ! -d "$ROOTPATH/binaries" ]; then
    echo "***creating binaries"
    mkdir "$ROOTPATH/binaries"
fi

cp "$ROOTPATH/composer_dev.json" "$ROOTPATH/composer.json"

if [ ! -f "$ROOTPATH/binaries/composer.phar" ]; then
    echo "***downloading composer"
    cd "$ROOTPATH/binaries"
    curl -sS https://getcomposer.org/installer | php >/dev/null 2>&1
    cd "$ROOTPATH"

    echo "***running composer install dev"
    php "$ROOTPATH/binaries/composer.phar" install --dev >/dev/null 2>&1
else
    echo "***running composer update dev"
    php "$ROOTPATH/binaries/composer.phar" update --dev >/dev/null 2>&1
fi

if [ ! -f "$ROOTPATH/binaries/phpDocumentor.phar" ]; then
    echo "***downloading phpDocumentor"
    cd "$ROOTPATH/binaries"
    wget -q http://phpdoc.org/phpDocumentor.phar
    cd "$ROOTPATH"
fi

cd "$ROOTPATH"
php "$ROOTPATH/binaries/phpDocumentor.phar"  >/dev/null 2>&1
if [ ! -d "$ROOTPATH/binaries" ]; then
    mkdir -p "/var/www/dev/docs/$CI_COMMIT_REF_NAME"
fi
rsync -vhru --delete-after ./docs/development/* "/var/www/dev/docs/$CI_COMMIT_REF_NAME/"

