#!/bin/bash
ROOTPATH="$1"
CI_COMMIT_REF_NAME="$2"
CI_ENVIRONMENT_SLUG="$3"
USERNAME=`whoami`

eval $(ssh-agent -s)
ssh-add /home/gitlab-runner/id_rsa_nxcore

echo "Reviewing $CI_COMMIT_REF_NAME in $ROOTPATH"

if [ ! -d "$ROOTPATH" ]; then
    mkdir -p "$ROOTPATH"
    cd "$ROOTPATH"
    git clone git@nxfifteen.me.uk:nx-fitness/nxfitness-core.git ./
else
    cd "$ROOTPATH"
fi

echo "Working in $ROOTPATH as $USERNAME"
cd "$ROOTPATH"

echo "Clearing changes"
git clean -df
echo "Checking out source"
git checkout -- .
echo "Checking out $CI_COMMIT_REF_NAME"
git checkout $CI_COMMIT_REF_NAME
echo "Making sure we're up-to-date"
git pull

echo "Checking Binaries"
if [ ! -d "$ROOTPATH/binaries" ]; then
    echo "***creating binaries"
    mkdir "$ROOTPATH/binaries"
fi

echo "Checking Composer"
cp "$ROOTPATH/composer_dev.json" "$ROOTPATH/composer.json"

if [ ! -f "$ROOTPATH/binaries/composer.phar" ]; then
    echo "***downloading composer"
    cd "$ROOTPATH/binaries"
    cp /home/gitlab-runner/tools/composer.phar ./
    cd "$ROOTPATH"

    echo "***running composer install dev"
    php "$ROOTPATH/binaries/composer.phar" install --dev >/dev/null 2>&1
else
    echo "***running composer update dev"
    php "$ROOTPATH/binaries/composer.phar" update --dev >/dev/null 2>&1
fi

echo "Checking phpDocumentor"
if [ ! -f "$ROOTPATH/binaries/phpDocumentor.phar" ]; then
    echo "***downloading phpDocumentor"
    cd "$ROOTPATH/binaries"
    cp /home/gitlab-runner/tools/phpDocumentor.phar ./
    cd "$ROOTPATH"
fi

echo "Running phpDocumentor"
cd "$ROOTPATH"
php "$ROOTPATH/binaries/phpDocumentor.phar"  >/dev/null 2>&1
if [ ! -d "$ROOTPATH/binaries" ]; then
    mkdir -p "/var/www/dev/docs/$CI_COMMIT_REF_NAME"
fi
rsync -hru --delete-after ./docs/development/* "/var/www/dev/docs/$CI_COMMIT_REF_NAME/"

killall -9 ssh-agent
