#!/bin/bash
ROOTPATH="$1"

eval $(ssh-agent -s)

ssh-add $HOME/id_rsa_nxcore

if [ ! -d "$ROOTPATH/binaries" ]; then
    echo "creating binaries"
    mkdir "$ROOTPATH/binaries"
fi

if [ ! -f "$ROOTPATH/binaries/composer.phar" ]; then
    echo "downloading composer"
    cd "$ROOTPATH/binaries"
    curl -sS https://getcomposer.org/installer | php #>/dev/null 2>&1
    cd "$ROOTPATH"
fi

echo "running composer install dev"
php "$ROOTPATH/binaries/composer.phar" install --dev #>/dev/null 2>&1

FROMTAG=""
CURRENTCOMIT=`git rev-parse --verify HEAD`
if [ -f "$ROOTPATH/docs/wiki.core/.lastChangeLog" ]; then
    LASTCOMMIT=`cat "$ROOTPATH/docs/wiki.core/.lastChangeLog"`

    if [ "$LASTCOMMIT" != "$CURRENTCOMIT" ]; then
        FROMTAG="--tag $LASTCOMMIT"
    fi
fi

cd "$ROOTPATH/docs/wiki.core"
git pull
cd "$ROOTPATH"

$HOME/git-changelog/tasks/command.js -p gitlab --file "$ROOTPATH/docs/wiki.core/change-log.md" $FROMTAG;
$HOME/git-changelog/tasks/command.js -p gitlab --file "$ROOTPATH/docs/wiki.core/extended-change-log.md" --extended;

echo "$CURRENTCOMIT" > "$ROOTPATH/docs/wiki.core/.lastChangeLog"

cd "$ROOTPATH/docs/wiki.core"
git add change-log.md extended-change-log.md .lastChangeLog
git commit -m "chore(changelog): Updated changelog files"
git push
