#!/bin/bash
ROOTPATH="$1"

eval $(ssh-agent -s)
ssh-add /home/nxad/.ssh/id_rsa_pss

if [ ! -d "$ROOTPATH/binaries" ]; then
    echo "creating binaries"
    mkdir "$ROOTPATH/binaries"
fi

if [ ! -f "$ROOTPATH/binaries/composer.phar" ]; then
    echo "downloading composer"
    cd "$ROOTPATH/binaries"
    curl -sS https://getcomposer.org/installer | php #>/dev/null 2>&1
    cd "$ROOTPATH"
fi

echo "running composer install dev"
php "$ROOTPATH/binaries/composer.phar" install --dev #>/dev/null 2>&1

FROMTAG=""
CURRENTCOMIT=`git rev-parse --verify HEAD`
if [ -f "$ROOTPATH/dev/.lastChangeLog" ]; then
    LASTCOMMIT=`cat "$ROOTPATH/dev/.lastChangeLog"`

    if [ "$LASTCOMMIT" != "$CURRENTCOMIT" ]; then
        FROMTAG="--tag $LASTCOMMIT"
    fi
fi

php "$ROOTPATH/vendor/phpdocumentor/phpdocumentor/bin/phpdoc" --progressbar;

echo "$ROOTPATH"

if [ ! -d "$ROOTPATH/binaries/phpdoc-md" ]; then
    echo "cloning phpdoc-md"
    cd "$ROOTPATH/binaries"
    git clone git@nxfifteen.me.uk:nx-style/phpdoc-md.git
    cd "$ROOTPATH/binaries/phpdoc-md"
    php "$ROOTPATH/binaries/composer.phar" install
    cd "$ROOTPATH"
else
    echo "updating phpdoc-md"
    cd "$ROOTPATH/binaries/phpdoc-md"
    git pull
    cd "$ROOTPATH"
fi

if [ ! -d "$ROOTPATH/docs/wiki.core" ]; then
    echo "creating markdown"
    cd "$ROOTPATH/docs/"
    git clone git@nxfifteen.me.uk:nx-fitness/nxfitness-core.wiki.git ./wiki.core
    cd "$ROOTPATH"
else
    echo "updating markdown"
    cd "$ROOTPATH/docs/wiki.core"
    pwd
    git pull
    cd "$ROOTPATH"
fi

php "$ROOTPATH/binaries/phpdoc-md/bin/phpdocmd" "$ROOTPATH/docs/development/structure.xml" "$ROOTPATH/docs/wiki.core/phpdoc/class"

cd "$ROOTPATH/docs/wiki.core"
rsync -vhru --delete-after ./ /var/www/dev/development/

ssh-add -D
ssh-add /home/nxad/.ssh/id_rsa_wiki

/home/nxad/gits/git-changelog/tasks/command.js -p gitlab --file "$ROOTPATH/docs/wiki.core/change-log.md" $FROMTAG;
/home/nxad/gits/git-changelog/tasks/command.js -p gitlab --file "$ROOTPATH/docs/wiki.core/extended-change-log.md" --extended;
git add change-log.md extended-change-log.md
git commit -m "chore(changelog): Updated changelog files"

git add .
git commit -m "chore(wiki): Updated phpdoc"
git push
